# Generated by Django 3.1.5 on 2021-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for this alias', unique=True, verbose_name='SLUG')),
                ('writer', models.CharField(blank=True, help_text='name of the press', max_length=10, verbose_name='WRITER')),
                ('article', models.TextField(max_length=500, verbose_name='ARTICLE')),
                ('href', models.TextField(verbose_name='HREF')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'db_table': 'news_list',
            },
        ),
    ]
