# Generated by Django 3.1.5 on 2021-01-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mynews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modify_date',), 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Date'),
        ),
    ]
