# Generated by Django 3.1.5 on 2021-01-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mynews', '0002_auto_20210129_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=500, verbose_name='TITLE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.TextField(blank=True, help_text='name of the press', max_length=10, verbose_name='WRITER'),
        ),
    ]
