# Generated by Django 3.1.5 on 2021-01-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mynews', '0003_auto_20210131_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
